### ISSUE TITLE
Fable2 is awesome!

### ISSUE THREAD

**Issue by whitetigle** [fable-compiler/fable-compiler.github.io#29]
but... Alfonso is currently sleeping (or at least pretending) and I wanted so much to improve Fable web site with Fulma in Full Wondercolors. 

But I ran into 3 problems:
1 - I'm a little bit tired because of vodka and loud music coming from my German friends upstairs
2 - I get this strange error which I tried to understand but due to my currently very limited non-MVP powers I can't solve. 

```shell
[0] fable: Compilation succeeded at 01:58:52 (21.126 s)
[0] TypeError: (0 , _Navbar.root) is not a function
[0]     at render (C:\Users\conta\Documents\workspace\fable-compiler.github.io\build\Main.js:66:210)
[0]     at renderHomePage (C:\Users\conta\Documents\workspace\fable-compiler.github.io\build\Main.js:131:3)
[0]     at Object.<anonymous> (C:\Users\conta\Documents\workspace\fable-compiler.github.io\build\Main.js:135:1)
[0]     at Module._compile (module.js:652:30)
[0]     at Object.Module._extensions..js (module.js:663:10)
[0]     at Module.load (module.js:565:32)
[0]     at tryModuleLoad (module.js:505:12)
[0]     at Function.Module._load (module.js:497:3)
[0]     at Module.require (module.js:596:17)
[0]     at require (internal/module.js:11:18)
```

The third problem is obviously the most important one.

**Comment by alfonsogarciacaro** [comment]
I cannot reproduce, did you run the following commands?

```shell
yarn
yarn start-all
```

(I just pushed a small update to README and scripts, but it should have worked before too.)
