### ISSUE TITLE
Add dependencies for building the website to readme

### ISSUE THREAD

**Issue by fbehrens** [fable-compiler/fable-compiler.github.io#46]
Hi dear maintainer,

I just wanted to see how this nice website is created, `npm install` fails,

and the output looks like it depends on `python` or can't be build on `win32`.

It is not important for me, but a little comment here would come via PR to the readme, and avoid this experience to other's

Thanks for the nice website, cheers Frank

**Comment by alfonsogarciacaro** [comment]
Hi @fbehrens! Thanks for the nice words. I assume this is because of node-gyp trying to build some native dependencies in C/C++ (likely oniguruma). You can have a look for Windows intructions here: https://github.com/nodejs/node-gyp#on-windows

I'll update the README :+1:

**Comment by fbehrens** [comment]
Sorry @alfonsogarciacaro , i forgot the "attachment", here is ->
```
10> npm install

> oniguruma@7.2.0 install C:\open\fable-compiler.github.io\node_modules\oniguruma
> node-gyp rebuild


C:\open\fable-compiler.github.io\node_modules\oniguruma>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:282:31
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\open\fable-compiler.github.io\node_modules\oniguruma
gyp ERR! node -v v10.16.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN rollback Rolling back readable-stream@2.3.6 failed (this is probably harmless): EPERM: operation not permitted, scandir 'C:\open\fable-compiler.github.io\node_modules\fsevents\node_modules'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oniguruma@7.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oniguruma@7.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\imynv\AppData\Roaming\npm-cache\_logs\2019-08-16T20_12_35_875Z-debug.log
```

**Comment by cartermp** [comment]
This seems resolved, as the readme is updated and all the commands work.

As a bonus, you can open in a gitpod environment and it all gets automated for you!
